name: Daily Connect redeploy nudge

on:
  schedule:
    # 8:45 AM America/Chicago (DST Mar–Oct)
    - cron: "45 13 * 3-10 *"
    # 8:45 AM America/Chicago (Standard Nov–Feb)
    - cron: "45 14 * 11,12,1,2 *"
  workflow_dispatch:

jobs:
  nudge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m 'chore: daily redeploy nudge [skip ci]'

      - name: Push to default branch
        run: |
          git push origin "HEAD:${{ github.event.repository.default_branch }}"